[package]
name = "procrs"
version = "0.2.0"
authors = ["Josh Driver <keeperofdakeys@gmail.com>"]

[dependencies]
getopts = "0.2"
prettytable-rs = "^0.6"

[[bin]]
name="psq"
path="src/psq/main.rs"

[lib]
name="procrs"
path="src/procrs/lib.rs"
