(function() {var implementors = {};
implementors['libc'] = [];implementors['procrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='procrs/pid/struct.Pid.html' title='procrs::pid::Pid'>Pid</a>",];implementors['procrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='procrs/pid/struct.Pid.html' title='procrs::pid::Pid'>Pid</a>",];implementors['procrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='procrs/pid/struct.Pid.html' title='procrs::pid::Pid'>Pid</a>",];implementors['procrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='procrs/pid/struct.Pid.html' title='procrs::pid::Pid'>Pid</a>",];implementors['procrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='procrs/pid/struct.Pid.html' title='procrs::pid::Pid'>Pid</a>",];implementors['procrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='procrs/pid/struct.Pid.html' title='procrs::pid::Pid'>Pid</a>",];implementors['procrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='procrs/pid/struct.Pid.html' title='procrs::pid::Pid'>Pid</a>",];implementors['procrs'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='procrs/pid/struct.Pid.html' title='procrs::pid::Pid'>Pid</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
